# Statistical Analysis Part I

Introduction
Statistical analysis is the process of collecting, organizing, analyzing, and interpreting data to discover patterns, relationships, and meaningful insights that support decision-making.
It’s about turning raw numbers into useful information. Instead of just having data, you use methods to understand what the data is telling you.
Statistical analysis is built on the idea of summarizing data and making conclusions using concepts from Statistics.
In the following analysis, we perform a squential statistical analysis that will help the basic to advanced learners with the help of Python. 
We have used CARS dataset to analyse and obtain the results.

In [3]:
#importing two libraries pandas and numpy for statistical analysis  
import pandas as pd
import numpy as np

In [7]:
# Reading dataset from local disk where file is saved. You should use 'r' before quotation marks of path so that slashes can be reversed. This is requirement of path
# File can be read in any format including csv, excel, SAS, Stata. We just need to give function of i.e. read_csv or read_sas etc
# If path does not recognize. upload your file in Jupypter and then read it by looking where your Jypyter is installed.
cars= pd.read_excel(r"C:\Users\Admin\Downloads\CARS.xlsx")

In [11]:
# .head() is a function to read first five observations. You can increase that number by inserting values in bracket i.e. (10)
cars.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197

In [13]:
# The function .head() is to read last five observations. You can increase that number by inserting values in bracket i.e. (10)
cars.tail()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186

In [47]:
# We want to know the number of observations and colums.
cars.shape

(428, 15)

In [15]:
# .info() function provides basic information about variables and their types including fload, integers and object. This is crucial in knwoing types of variables in your dataset
# It also tells number of obvservations in each variable and missing, nonmissing values.
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Make         428 non-null    object
 1   Model        428 non-null    object
 2   Type         428 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    int64
 6   Invoice      428 non-null    int64
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   428 non-null    int64
 10  MPG_City     428 non-null    int64
 11  MPG_Highway  428 non-null    int64
 12  Weight       428 non-null    int64
 13  Wheelbase    428 non-null    int64
 14  Length       428 non-null    int64
dtypes: float64(2), int64(8), object(5)
memory usage: 50.3+ KB

In [17]:
# .columns tells about total variables and name of variables in actual which are written in dataset. 
# Important thing is they are shown in quotation marks and if you use them in further analysis, they can be copied. It will help avoid small or big cap problem
cars.columns

Index(['Make', 'Model', 'Type', 'Origin', 'DriveTrain', 'MSRP', 'Invoice',
       'EngineSize', 'Cylinders', 'Horsepower', 'MPG_City', 'MPG_Highway',
       'Weight', 'Wheelbase', 'Length'],
      dtype='object')

In [27]:
# If you want to view only on variable then you can use the following code by connecting dataset name with variable name
cars.Make

0      Acura
1      Acura
2      Acura
3      Acura
4      Acura
       ...
423    Volvo
424    Volvo
425    Volvo
426    Volvo
427    Volvo
Name: Make, Length: 428, dtype: object

In [19]:
# if you want to analyze using any statistic for specific variable i.e. mean, median, sum etc. 
cars['EngineSize'].mean()

3.1967289719626164

In [21]:
# if you want to mean/median/min/max of each numeric variable 
cars.mean(numeric_only=True)

MSRP           32774.855140
Invoice        30014.700935
EngineSize         3.196729
Cylinders          5.807512
Horsepower       215.885514
MPG_City          20.060748
MPG_Highway       26.843458
Weight          3577.953271
Wheelbase        108.154206
Length           186.362150
dtype: float64

In [25]:
# If you want mean/median/min/max of each row rather columns
cars.mean(axis = 1,numeric_only=True)

0      7534.25
1      4889.30
2      5541.24
3      6769.02
4      8723.75
        ...
423    8276.24
424    8668.43
425    9205.79
426    5410.59
427    7263.75
Length: 428, dtype: float64

In [33]:
# We want descriptive statistics of all numeric variables. 
# Further output has more decimal places. So, we can use .round() function to reduce decimal places. We can add .round(2) upto two decimal places
cars.describe().round()

,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
count,428.0,428.0,428.0,426.0,428.0,428.0,428.0,428.0,428.0,428.0
mean,32775.0,30015.0,3.0,6.0,216.0,20.0,27.0,3578.0,108.0,186.0
std,19432.0,17642.0,1.0,2.0,72.0,5.0,6.0,759.0,8.0,14.0
min,10280.0,9875.0,1.0,3.0,73.0,10.0,12.0,1850.0,89.0,143.0
25%,20334.0,18866.0,2.0,4.0,165.0,17.0,24.0,3104.0,103.0,178.0
50%,27635.0,25294.0,3.0,6.0,210.0,19.0,26.0,3474.0,107.0,187.0
75%,39205.0,35710.0,4.0,6.0,255.0,21.0,29.0,3978.0,112.0,194.0
max,192465.0,173560.0,8.0,12.0,500.0,60.0,66.0,7190.0,144.0,238.0

In [41]:
# We can also transpose out output as required by research thesis/papers. We can add only .T at the end of code
cars.describe().round().T

,count,mean,std,min,25%,50%,75%,max
MSRP,428.0,32775.0,19432.0,10280.0,20334.0,27635.0,39205.0,192465.0
Invoice,428.0,30015.0,17642.0,9875.0,18866.0,25294.0,35710.0,173560.0
EngineSize,428.0,3.0,1.0,1.0,2.0,3.0,4.0,8.0
Cylinders,426.0,6.0,2.0,3.0,4.0,6.0,6.0,12.0
Horsepower,428.0,216.0,72.0,73.0,165.0,210.0,255.0,500.0
MPG_City,428.0,20.0,5.0,10.0,17.0,19.0,21.0,60.0
MPG_Highway,428.0,27.0,6.0,12.0,24.0,26.0,29.0,66.0
Weight,428.0,3578.0,759.0,1850.0,3104.0,3474.0,3978.0,7190.0
Wheelbase,428.0,108.0,8.0,89.0,103.0,107.0,112.0,144.0
Length,428.0,186.0,14.0,143.0,178.0,187.0,194.0,238.0

In [43]:
# Previous code only provide 25%, 50%, 75% percentiles. If we want to extend our percentiles, we can customize as per our requirements
cars.describe(include=[np.number], percentiles=[.01, .05, .10, .25, .5, .75, .9, .95, .99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max
MSRP,428.0,32774.855140,19431.716674,10280.0,11191.45,13691.00,15484.5,20334.250,27635.0,39205.00,52781.0,72864.25,93659.00,192465.0
Invoice,428.0,30014.700935,17642.117750,9875.0,10659.01,12836.65,14459.7,18866.000,25294.5,35710.25,48103.3,66471.95,87244.27,173560.0
EngineSize,428.0,3.196729,1.108595,1.3,1.50,1.70,1.8,2.375,3.0,3.90,4.6,5.30,6.00,8.3
Cylinders,426.0,5.807512,1.558443,3.0,4.00,4.00,4.0,4.000,6.0,6.00,8.0,8.00,9.50,12.0
Horsepower,428.0,215.885514,71.836032,73.0,103.00,115.00,130.0,165.000,210.0,255.00,302.0,338.25,469.71,500.0
MPG_City,428.0,20.060748,5.238218,10.0,12.00,14.00,15.0,17.000,19.0,21.25,26.0,29.00,35.73,60.0
MPG_Highway,428.0,26.843458,5.741201,12.0,16.27,18.00,20.0,24.000,26.0,29.00,33.3,36.00,43.73,66.0
Weight,428.0,3577.953271,758.983215,1850.0,2211.20,2513.00,2678.7,3104.000,3474.5,3977.75,4494.4,4995.45,5824.73,7190.0
Wheelbase,428.0,108.154206,8.311813,89.0,93.00,95.35,99.0,103.000,107.0,112.00,119.0,123.00,133.00,144.0
Length,428.0,186.362150,14.357991,143.0,153.27,163.00,168.0,178.000,187.0,194.00,204.0,212.00,222.00,238.0

In [39]:
#Finally, we can also get our categorical values to observe each variable with maximum categories along with Mode of each category.
cars.describe(exclude=[np.number])

          Make     Model   Type Origin DriveTrain
count      428       428    428    428        428
unique      38       425      6      3          3
top     Toyota   G35 4dr  Sedan   Asia      Front
freq        28         2    262    158        226

In [ ]:
# Bygroup analysis using categorical variable analysis is performed in Statistical Inference II.